apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: steam-headless
spec:
  serviceName: "steam-headless"
  replicas: 1
  selector:
    matchLabels:
      app: steam-headless
  template:
    metadata:
      labels:
        app: steam-headless
    spec:
      nodeSelector:
        livekit.io/node-pool: cloud-media
      tolerations:
      - key: "livekit.io/node-pool"
        operator: "Equal"
        value: "cloud-media"
        effect: "NoSchedule"
      hostNetwork: true
      securityContext:
        fsGroup: 1000
      imagePullSecrets:
        - name: dockerhub
      containers:
      - name: steam-headless
        securityContext:
          privileged: true
        image: livekit/steam-test:latest
        resources: #Change CPU and Memory below
          requests:
            memory: "12Gi"
            cpu: "7000m"
          limits:
            memory: "12Gi"
            cpu: "7000m"
            # nvidia.com/gpu: 1 #If you're using a nvidia GPU, add it here
        volumeMounts:
        - name: home-dir
          mountPath: /home/default/
        - name: games-dir
          mountPath: /mnt/games/
        - name: input-devices
          mountPath: /dev/input/
        - name: dshm
          mountPath: /dev/shm
        env: #Environmental Vars
        - name: NAME
          value: 'SteamHeadless'
        - name: TZ
          value: 'America/New_York'
        - name: USER_LOCALES
          value: 'en_US.UTF-8 UTF-8'
        - name: DISPLAY
          value: ':55'
        - name: SHM_SIZE
          value: '2G'
        - name: DOCKER_RUNTIME
          value: 'nvidia'
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: UMASK
          value: '000'
        - name: USER_PASSWORD
          value: 'password' #changeme
        - name: MODE
          value: 'primary'
        - name: WEB_UI_MODE
          value: 'none'
        - name: ENABLE_VNC_AUDIO
          value: 'false'
        - name: PORT_NOVNC_WEB
          value: '8083'
        - name: NEKO_NAT1TO1
          value: ''
        - name: ENABLE_SUNSHINE
          value: 'true'
        - name: SUNSHINE_USER
          value: 'sam'
        - name: SUNSHINE_PASS
          value: 'password'
        - name: ENABLE_EVDEV_INPUTS
          value: 'true'
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: 'all'
        - name: NVIDIA_VISIBLE_DEVICES
          value: 'all'
      volumes:
      - name: home-dir
        persistentVolumeClaim:
          claimName: home
      - name: games-dir
        persistentVolumeClaim:
          claimName: games
      - name: input-devices
        hostPath:
          path: /dev/input/
      - name: dshm
        emptyDir:
          medium: Memory
